image: node:10.15.3

clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build
        caches:
            - node
        script:
          - npm install
          - npm run build
          - npm run test
          - npm run lint:check
  branches:
    master:
      - step:
          name: Archive
          script:
            - git archive --format=tar.gz master -o application.tar.gz
          artifacts:
              - application.tar.gz
      - step:
          name: Deploy
          deployment: staging
          caches:
            - node
          script:
            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_APP_NAME: flexcavo-webshop-staging
                HEROKU_API_KEY: $HEROKU_API_KEY
                ZIP_FILE: application.tar.gz
  tags:
    prod-v*:                  
      - step:          
          name: Archive
          script: 
            - git archive --format=tar.gz HEAD -o application.tar.gz
          artifacts:
            - application.tar.gz
      - step:
          name: Deploy
          deployment: production
          script:
            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_APP_NAME: flexcavo-webshop-prod
                HEROKU_API_KEY: $HEROKU_API_KEY
                ZIP_FILE: application.tar.gz
  custom:
    deploy-tag-to-prod:
      - variables:   
        - name: PROD_TAG_VERSION
      - step:
          name: Archive
          script:
            - git checkout prod-${PROD_TAG_VERSION}
            - git archive --format=tar.gz HEAD -o application.tar.gz
          artifacts:
              - application.tar.gz
      - step:
          name: Deploy
          deployment: production
          caches:
            - node
          script:
            - git checkout prod-${PROD_TAG_VERSION}
            - export BITBUCKET_COMMIT=`git rev-parse --short HEAD` #required so that heroku will show the correct commit id in the protal
            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_APP_NAME: flexcavo-webshop-prod
                HEROKU_API_KEY: $HEROKU_API_KEY
                ZIP_FILE: application.tar.gz
      